version: '2'
services:
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: nginx.dockerfile
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx-php
    volumes:
      - .:/app:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://node.docker.amazee.io

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    depends_on:
      - cli
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx-php

networks:
  amazeeio-network:
    external: true